apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/julianxalessio/kubernetes.git   # <-- anpassen
    targetRevision: main                                  # <-- anpassen
    path: apps/monitoring                       # Ordner mit Chart.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # CRDs sind groß -> Server-Side Apply nötig
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Julianxalessio/kubernetes.git 
    targetRevision: main                                  
    path: apps/databases         

  destination:
    server: https://kubernetes.default.svc
    namespace: databases-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.34.1

    helm:
      releaseName: vault
      valuesObject:
        server:
          enabled: true

          ha:
            enabled: true
            replicas: 1

            raft:
              enabled: true

          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: local-path

          auditStorage:
            enabled: true
            size: 10Gi
            storageClass: local-path

          injector:
            enabled: true

          ui:
            enabled: true

          ingress:
            enabled: true
            ingressClassName: traefik

            hosts:
              - host: vault.infra.lomdev.ch
                paths:
                  - /
  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true