apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/julianxalessio/kubernetes.git   # <-- anpassen
    targetRevision: main                                  # <-- anpassen
    path: apps/monitoring                       # Ordner mit Chart.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # CRDs sind groß -> Server-Side Apply nötig
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: databases-namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Julianxalessio/Databases-ArgoCD.git   
    targetRevision: main                                  
    path: .                   

  destination:
    server: https://kubernetes.default.svc
    namespace: databases-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 